spring.application.name: keycloak-authtest
server:
  port: 8080

logging:
  level:
    org.springframework.security.saml2: TRACE
    org.springframework.security.web.authentication: TRACE
    org.springframework.security.oauth2.client: TRACE